export { questions };
  const questions = [
     {
    questionId: "1",
    questionText: "which of the following is an example of a discrete random variable?",
    optionA: "the exact height of student in a classroom(measured in cm)",
    optionB: "The number of student presents in a classroom",
    optionC: "The amount of fuel in a car's tank (in litres)",
    optionD: "he time taken to finished marathon (in hours)",
    correct:"B",
    
  },
  {
    questionId: "2",
    questionText: "if we examine three different class squantially, and documentn the result in each of examination as F(Female) and M(Male)then the sample space is  s = { FFF, FFM, FMF, FMM, MFF, MFM, MMF, MMM } ? ",
optionA: "4",
    optionB: "6",
    optionC: "8",
    optionD: "10",
    correct:"C",
  },
  {
    questionId: "3",
    questionText: "A coin is tossed twice. what is the probability that atleast one head occurs ? ",
    optionA: "1/4",
    optionB: "1/2",
    optionC: "3/4",
    optionD: "1",
    correct:"C",
  },
  {
    questionId: "4",
    questionText: "what is the probability of getting a total of 7 or 11 when a pair of fair dice tossed ? ",
    optionA: "1/6",
    optionB: "1/9",
    optionC: "2/9",
    optionD: "5/36 ",
    correct:"B",
  }
  ,
  {
  questionId: "5",
  questionText: "if a six men are to be arranged in a line without any restriction the total number of arrangement is ? ",
  optionA: "120",
  optionB: "360",
  optionC: "720",
  optionD: "1440 ",
  correct:"C",
  },
  {
  questionId: "6",
  questionText: "the sample space of an experiment refers to : ",
  optionA: "subset of all possible events",
  optionB: "All possible outcomes  of the experiment ",
  optionC: "the most frequent outcome",
  optionD: "None of the options  ",
  correct:"B",
  },
  {
  questionId: "7",
  questionText: "which of the following is an example of probability ? ",
  optionA: "Rolling a die",
  optionB: "Tossing a coin",
  optionC: "selecting a card from a deck",
  optionD: "All of the above ",
  correct:"D",
  },
  {
  questionId:"8",
  questionText: "if a fair of coins tossed three times,what is the probabilityof getting exactly 2 heads ?",
  optionA: "1/4",
  optionB: "3/8",
  optionC: "1/2",
    optionD: "5/8 ",
  correct:"A",
  
  },
  {
  questionId:"9",
  questionText: "which of the following is an example of ordinal categorical data ? ",
  optionA: "Bload group (A,B,AB,O)",
  optionB: "Nationality",
  optionC: "Educational Level (Primary,secondary,University)",
    optionD: "Favorite Fruits (Mango,Apple,Banana)",
  correct:"B",
  },
  {
  questionId: "10",
  questionText: "Which type of quantitative data represents Values that can take on any value within a range ?",
  optionA: "Ordinal data",
  optionB: "Nominal data",
  optionC: "discrete data",
    optionD: "continues data ",
  correct:"D",
  },
   {
 questionId: "11",
 questionText: " Find the value of r if 5(r-3) = 20.",
 optionA: "1",
 optionB: "4",
 optionC: "7",
     optionD: "12",
 correct:"C",
  },
    {
 questionId: "12",
 questionText: "For the dataset: 10,15,20,25,30,35,40 what is the Inter Quatile Range (IQR)?  ",
 optionA: "10",
 optionB: "15",
 optionC: "20",
    optionD: "25",
 correct:"D",
  },
     {
 questionId: "13",
 questionText: "Which visualisation is most suitable for detecting outliers in numerical data :",
 optionA: "Bar chat ",
 optionB: "Boxplot",
 optionC: "Pie chart",
 optionD: "Line graph",
 correct:"B",
 
}, {
 questionId: "14",
 questionText: "Which of the following best descrive the purpose of Exploratory Data Analysis (EDA) ? ",
 optionA: "to apply the advanced machine learning algorithms ",
 optionB: "To summarize,Visualise,and understand data before formal modelling",
 optionC: "collect raw data from an experiment ",
       optionD: "All of the above ",
 correct:"D",
}
  ,
  {
    questionId:"15",
    questionText: " In a probability model, the probability of the empty set  is always:",
    optionA: "0",
    optionB: "1",
    optionC: " undefined",
    optionD: "Depends on the sample space",
    correct:"C",
  },
  {
  questionId:"16",
  questionText: "which of the following best descrive a Negative Random Variables ?",
  optionA: "The number of head  in n of a tosses of a fair coin ",
  optionB: "The number of trials needed to achieve a fixed number of success in independent bernouli trials ",
  optionC: "The number of students iarriving at a library per hour ",
    optionD: "The lifetime of a light bulb in measured in hour",
  correct:"B",
  },
    {
  questionId:"17",
  questionText: "Which of the following statements is true about permutation and combination ?",
  optionA: "Combination consider the order of selection.",
  optionB: "Permutation consider the order of selection",
  optionC: "Both permuation and combination ignored the order of selection ",
  optionD: "Neither permutation nor combination consider the order of selection", 
  correct:"A",
  },
      {
  questionId:"18",
  questionText: "Which of the following statements is false ? :",
  optionA: "Every one-to-one function is a function",
  optionB: "Every function has a domain",
  optionC: "A function can have the same outputs for different inputs",
  optionD:"Every function has an inverse",
  correct:"D",
  },
   {
  questionId:"19",
  questionText: "Differentiation from the first principle is based on the concept of :",
  optionA: "Integration",
  optionB: "Limits",
  optionC: "Algebraic manuplation",
  optionD:"Trigonimetry" ,
  correct:"B",
 },  {
  questionId:"20",
  questionText: "The instantaneous rate of change is geometrically represented by the slope of the:",
  optionA: "Secant line",
  optionB: "Tanget line",
  optionC: "Normal line",
  optionD:"Asymptote",
  correct:"B",
 },  {
  questionId:"21",
  questionText: "The chain rule is mainly used to differentiate : ",
  optionA: "Linear functions",
  optionB: "Functions of a single variable",
  optionC: "Composite functions",
  optionD:"Constant functions ",
  correct:"C",
  },
  {
  questionId:"22",
  questionText: "The derivative of a function at a point represent the :",
  optionA: "Area of the curve",
  optionB: "Average rate of change",
  optionC: "Instantaneous rate of change",
  optionD:"Total change",
  correct:"C",
  },
   /* 
  {
    questionId:"",
    questionText: "",
    optionA: "",
    optionB: "",
    optionC: "",
     optionD:""
 }
  */ {
   questionId:"23",
   questionText: "Implicit differentiation is used when : ",
   optionA: "The variable y is isolated",
   optionB: "A function is written expilicity as y = f(x) ",
   optionC: "y is defined indirectly in an equation ",
    optionD: "only constants are involved",
    correct:"C"
  },
   {
   questionId:"24",
   questionText: "The derivative measures how quantity changes with respect to: ",
   optionA: "Time only",
   optionB: "Distance only",
   optionC: "Another variables",
     optionD: "Area",
    correct:"C"
  },
    {
   questionId:"25",
   questionText: "Which of the following quatities is NOT repersented by a derivative ? ",
   optionA: "Velocity",
   optionB: "Acceleration",
   optionC: "Slope of a curve ",
      optionD: "Area under curve",
    correct:"D"
}, {
   questionId:"26",
   questionText: "Which of the following best explains why is a constant of integration added when evaluating indefite integral",
   optionA: "Integration always produces new constants",
   optionB: "Differentiation removes constants",
   optionC: "Different antiderivatives differ only by a constant",
      optionD: "Constant simplify integration",
    correct:"C"
  },
     {
   questionId:"27",
   questionText: "Integration by subsititution is most appropriate when:",
   optionA: "The integrand is a polynomial",
   optionB: "The integrand contains a composite function",
   optionC: "The limit of integration are constants",
       optionD: "The integrand is a rational function",
    correct:"B"
  },
  {
   questionId:"28",
   questionText: " Integration by parts is mainly used when the integrand is :",
   optionA: " A rational function",
   optionB: " A product of two functions ",
   optionC: " A constant function ",
    optionD:" A composite function "
  },
   {
   questionId:"29",
   questionText: "The quotient rule is applied when a function is written as: ",
   optionA: " A polynomial",
   optionB: " A fraction of two functions ",
   optionC: " A trigonometric function",
     optionD: "An exponential function",
    correct:"A"
  },
    {
   questionId:"30",
   questionText: "Which of the following is an example of an explicit function ? ",
   optionA: " 20xy +7y = 9",
   optionB: "xy + y = 1",
   optionC: "y = 2x + 3",
      optionD: "x+y = xy",
    correct:"C"
  },

  /*
 {
      questionId: "32",
      questionText: "Programming language is simple ",
      optionA: "Yes",
      optionB: "NO",
      optionC: "might be true ",
    optionD: "not at all ",
      Correct:"C"
}
*/

];